using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class Column : AllorsClassColumn, AllorsInterfaceColumn
	{		
		public Column(AllorsStrategy allors) : base(allors) {}

		public static Column Instantiate (AllorsSession session, string id)
		{
			return (Column) session.Instantiate(id);		
		}
	}
}