using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class DateTimeCell : AllorsClassDateTimeCell, AllorsInterfaceDateTimeCell
	{		
		public DateTimeCell(AllorsStrategy allors) : base(allors) {}

		public static DateTimeCell Instantiate (AllorsSession session, string id)
		{
			return (DateTimeCell) session.Instantiate(id);		
		}
	}
}