using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class IntCell : AllorsClassIntCell, AllorsInterfaceIntCell
	{		
		public IntCell(AllorsStrategy allors) : base(allors) {}

		public static IntCell Instantiate (AllorsSession session, string id)
		{
			return (IntCell) session.Instantiate(id);		
		}
	}
}