using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class Library : AllorsClassLibrary, AllorsInterfaceLibrary
	{		
		public Library(AllorsStrategy allors) : base(allors) {}

		public static Library Instantiate (AllorsSession session, string id)
		{
			return (Library) session.Instantiate(id);		
		}
	}
}