using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class Row : AllorsClassRow, AllorsInterfaceRow
	{		
		public Row(AllorsStrategy allors) : base(allors) {}

		public static Row Instantiate (AllorsSession session, string id)
		{
			return (Row) session.Instantiate(id);		
		}
	}
}