using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class StringCell : AllorsClassStringCell, AllorsInterfaceStringCell
	{		
		public StringCell(AllorsStrategy allors) : base(allors) {}

		public static StringCell Instantiate (AllorsSession session, string id)
		{
			return (StringCell) session.Instantiate(id);		
		}
	}
}