using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class StringParameter : AllorsClassStringParameter, AllorsInterfaceStringParameter
	{		
		public StringParameter(AllorsStrategy allors) : base(allors) {}

		public static StringParameter Instantiate (AllorsSession session, string id)
		{
			return (StringParameter) session.Instantiate(id);		
		}
	}
}