using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class DateParameter : AllorsClassDateParameter, AllorsInterfaceDateParameter
	{		
		public DateParameter(AllorsStrategy allors) : base(allors) {}

		public static DateParameter Instantiate (AllorsSession session, string id)
		{
			return (DateParameter) session.Instantiate(id);		
		}
	}
}