using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class Program : AllorsClassProgram, AllorsInterfaceProgram
	{		
		public Program(AllorsStrategy allors) : base(allors) {}

		public static Program Instantiate (AllorsSession session, string id)
		{
			return (Program) session.Instantiate(id);		
		}
	}
}