using AllorsDomains;
using Allors;
using Allors.Meta;
using Iseries.AllorsGenerated;

namespace Iseries
{
	// Generated file. 
	// Do not edit this file, changes will be overwritten.
	public partial class Table : AllorsClassTable, AllorsInterfaceTable
	{		
		public Table(AllorsStrategy allors) : base(allors) {}

		public static Table Instantiate (AllorsSession session, string id)
		{
			return (Table) session.Instantiate(id);		
		}
	}
}